### ISSUE TITLE
Using Within Objective-C Project

### ISSUE THREAD

**Issue by alexsaidani** [entotsu/TKSubmitTransition#1]
I'm having problems getting the spinner to work when using this within an Objective-C project, works fine in the original Swift one and everything else works fine but the spinner in the Objective-C project.

Any ideas?

**Comment by hbj520** [comment]
yes,you are right

**Comment by danipralea** [comment]
+1

**Comment by pjebs** [comment]
I can't get it to work in a mixed project either.

**Comment by entotsu** [comment]
wow... +1

**Comment by pjebs** [comment]
just used this: https://github.com/wwdc14/HySubmitTransitionObjective-C

**Comment by entotsu** [comment]
Yesssssssssssss!!

**Comment by jesster2k10** [comment]
Please use the Objective-C version here https://github.com/wwdc14/HySubmitTransitionObjective-C
