### ISSUE TITLE
customised color?

### ISSUE THREAD

**Issue by Magrider** [entotsu/TKSubmitTransition#13]
Hi there, is that possible to make colour to be customised?  I know I can change the value, but I don't want to unlock the file. But I want to keep the pod file unchanged. Thanks

**Comment by n8stowell82** [comment]
you can style the button like this in your view controller (viewdidload): 
`loginButton.backgroundColor = UIColor.whiteColor()
 loginButton.normalBackgroundColor = UIColor.blueColor()
 loginButton.highlightedBackgroundColor = UIColor.greenColor()
 loginButton.normalCornerRadius = 0.0`
