### ISSUE TITLE
Failed to set user defined color

### ISSUE THREAD

**Issue by jonedavis** [entotsu/TKSubmitTransition#17]
I haven't had any luck using the Swift version of this.

I'm receiving the following output in the console:

`2015-11-12 16:16:19.825 SubmitTransition[8616:2039351] Failed to set (normalBackgroundColor) user defined inspected property on (SubmitTransition.TKTransitionSubmitButton): [<SubmitTransition.TKTransitionSubmitButton 0x7f98f0c264e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key normalBackgroundColor.
2015-11-12 16:16:19.826 SubmitTransition[8616:2039351] Failed to set (highlightedBackgroundColor) user defined inspected property on (SubmitTransition.TKTransitionSubmitButton): [<SubmitTransition.TKTransitionSubmitButton 0x7f98f0c264e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key highlightedBackgroundColor.`

**Comment by golan-fairfly** [comment]
TransitionSubmitButton.swift 

    @IBInspectable var normalBackgroundColor: UIColor = UIColor.whiteColor() {
        didSet {
            setBackgroundColor(normalBackgroundColor, forState: .Normal)
        }
    }

    @IBInspectable var highlightedBackgroundColor: UIColor = UIColor.whiteColor() {
        didSet {
            setBackgroundColor(normalBackgroundColor, forState: .Highlighted)
        }
    }

    func setBackgroundColor(color: UIColor, forState: UIControlState) {
        UIGraphicsBeginImageContext(CGSize(width: 1, height: 1))
        CGContextSetFillColorWithColor(UIGraphicsGetCurrentContext(), color.CGColor)
        CGContextFillRect(UIGraphicsGetCurrentContext(), CGRect(x: 0, y: 0, width: 1, height: 1))
        let colorImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        self.setBackgroundImage(colorImage, forState: forState)
    }

**Comment by theservo** [comment]
Thanks @golan-fairfly!

**Comment by jonedavis** [comment]
Thanks for the help!
