### ISSUE TITLE
Loading no time but when the answering server

### ISSUE THREAD

**Issue by HideCode7** [entotsu/TKSubmitTransition#19]
How can I make the button animation start when I click on it and end when you receive the response from the server ?

Thank you

**Comment by sarfrazb** [comment]
You can call `button.startLoadingAnimation()` right before you make your request.
Once you receive the response from the server, you can then call 
`button.startFinishingAnimation(1) {
// your completion code goes here
}`

One thing I had to be careful of was that if your server request is happening on a background thread, you'll have to jump to the main thread to call the finishing animation.

So, as an example:
```
func logIn() {
	button.startLoadingAnimation()

	async.background {

		let results = try! query.findObjects()
		if results.count == 0 {
			// insert alertView telling user that their details don't work
		}
		else {
			// return to main thread to complete login
			async.main {
				button.startFinishingAnimation(1) {
				let sb = UIStoryboard(name: "Main", bundle: nil)
	            		let vc = sb.instantiateViewController(withIdentifier: "MainVC")
				vc.transitioningDelegate = self
				UIView.animate(withDuration: 1, animations: { 
					self.present(vc, animated: false, completion: nil)
				})
		}
}
```
