### ISSUE TITLE
Using with Storyboard

### ISSUE THREAD

**Issue by rishabhtayal** [entotsu/TKSubmitTransition#2]
How can we use this library with Storyboard?

**Comment by stepan** [comment]
Hey @rishabhtayal, I have a pull request open that let's the custom button be used in a Storyboard. Hopefully @entotsu can look at it and merge it in.

**Comment by rishabhtayal** [comment]
👍

**Comment by entotsu** [comment]
#3 
@stepan PullRequest solved this issue!!
Thank you! :laughing:
