### ISSUE TITLE
Storyboard support

### ISSUE THREAD

**Issue by jamesallison** [entotsu/TKSubmitTransition#20]
Trying to use this with a button defined in a storyboard. Using `@IBOutlet weak var loginButton: TKTransitionSubmitButton!`, when `loginButton.startLoadingAnimation()` is called it crashes with `fatal error: unexpectedly found nil while unwrapping an Optional value.`

**Comment by jesster2k10** [comment]
@jamesallison Please double check that you have setup the `IBOutlet` correctly. I'll close this until further response
