### ISSUE TITLE
Seque to tabbar Controller

### ISSUE THREAD

**Issue by MartinQue** [entotsu/TKSubmitTransition#22]
I've been working on transitioning the button animation to a tabbar controller but no luck. Is there a way you can help me with this? Hw do i seque to the homeVC of my tabbar controller? 
Many thanks in advance :)

**Comment by nadimalam** [comment]
Hi, did you work this out as I'm having the same issue, i don't get the fading effect, the tab bar VC just suddenly displays the selected VC.
