### ISSUE TITLE
Cancelling animation

### ISSUE THREAD

**Issue by MartinQue** [entotsu/TKSubmitTransition#23]
Hi, this should be an easy one but can't seem to figure it out. Any help please. 

If for instance a login/ signup fails, how does one cancel animation? ... 

Thanks

**Comment by DeathRisker** [comment]
yourTkButton.stopLoadingAnimation()

**Comment by DeathRisker** [comment]
Sorry, go to the library source file TransitionSubmitButton.swift and add the following:
    public func stopLoadingAnimation(){
        self.spiner.stopAnimation()
    }
then you can use it

**Comment by DeathRisker** [comment]
You can implement a method in source file called stopLoadingAnimation() in TransitionSubmitButton.swift
public func stopLoadingAnimation(){
     self.spiner.stopAnimation()    
    self.returnToOriginalState()    }
I dont know why the author didn't add this useful method lol

**Comment by MaeseppTarvo** [comment]
There is -- setOrigianlState() does this.
