### ISSUE TITLE
Swift 3?

### ISSUE THREAD

**Issue by noisyscanner** [entotsu/TKSubmitTransition#29]
Hey, when will the Swift 3 version be coming out? As Xcode is now final and iOS 10 is out?

Cheers

**Comment by mofolo** [comment]
+1 Yep any support for Swift 3? Seems to break when updated through Pods.

**Comment by hdoria** [comment]
+1 here.

**Comment by telip007** [comment]
+1 here too.

**Comment by pandaxbacon** [comment]
@telip007 @hdoria 
I think you guys should check out RishabhTayal (Aug 3 commit) Updated for swift 3
It works fine! 
https://github.com/entotsu/TKSubmitTransition/tree/d7b6272044a7ee2ab02aa7179051c62cb45296e0
But it got reverted by @entotsu (I think there were errors after the merge, Xcode + Swift is a nightmare, i know that feel 👍)

**Comment by telip007** [comment]
In your version I can't see the spinner...

**Comment by ooleynich** [comment]
telip007 +1
After Xcode IB files auto update till device type

**Comment by smashkins** [comment]
+1

**Comment by TareqElMasri** [comment]
What is the status of this? Isn't there any workaround to make it work? Please answer!

**Comment by TareqElMasri** [comment]
Everyone, I fixed this issue and I uploaded in a new repository and made a new cocoa pod. I will remove them once the original makers merge my solution.
Until then, you can download it and use it from here: https://github.com/TareqElMasri/TKSubmitTransitionSwift3

**Comment by telip007** [comment]
@TareqElMasri please keep it updated :)

**Comment by adrianodiasx93** [comment]
+1 Spinner not showing.

**Comment by jesster2k10** [comment]
Swift 3 Should be working now :)
