### ISSUE TITLE
how to stop loading animation?

### ISSUE THREAD

**Issue by CoterJiesen** [entotsu/TKSubmitTransition#33]
i try to use function returnToOriginastate  ，but don't work。。。

**Comment by abdulla-allaith-7** [comment]
Same, using `returnToOriginalState()` or `setOriginalState()` both do NOT work!

**Comment by sarfrazb** [comment]
Both are working fine for me - I installed via CocoaPods
Do you have some code for context?

**Comment by nadimalam** [comment]
they both work for me too, however my button is a rectangle shape with box shape at the start and end of the button. However, when i use returnToOriginalState() it makes my button have rounded ends to it! How can i prevent this from happening?

**Comment by ptaking** [comment]
Stick to the dribble. It's a rounded button.
