### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by ptaking** [entotsu/TKSubmitTransition#37]
Xcode 8, Swift 3.0
![screen shot 2017-08-09 at 15 08 54](https://user-images.githubusercontent.com/12915431/29111500-bccad5fa-7d14-11e7-9516-fdd222c64b94.png)

**Comment by jesster2k10** [comment]
@ptaking The pod isn't updated for swift 3 just now, look at the `README` for how to install it with swift 3.0

**Comment by ptaking** [comment]
@jesster2k10 thanks.
