### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by mtaroco** [entotsu/TKSubmitTransition#39]
Build failing in xcode 9 with swift 4

**Comment by jesster2k10** [comment]
@mtaroco It's being worked on! Feel free to open a PR. In the meantime, you can set your project to build with Swift 3.2 if that's not an issue. Please send over a screenshot of the errors too

**Comment by sasquatchgit** [comment]
![error screenshot](https://user-images.githubusercontent.com/9585608/34930351-164339d6-f9ef-11e7-95f5-ceacb3e03caa.png)

**Comment by RishabhTayal** [comment]
I am going to start a branch `swift4` to support.

**Comment by RishabhTayal** [comment]
@mtaroco You can use the swift4 branch with cocoapods like this:

```
  pod 'TKSubmitTransition', :git => 'https://github.com/entotsu/TKSubmitTransition.git', :branch => 'swift4'
```
