### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by yumsmools** [entotsu/TKSubmitTransition#4]
Using this with iOS 9 and I had to make a few changes for swift 2.  It's working great except for the spinner not showing.  any ideas?

**Comment by alexsaidani** [comment]
Have you got this working - seem to be having a similar issue, the spinner doesn't show for me.

**Comment by adrianodiasx93** [comment]
+1
Perhaps it has something to do with the depreciation of `M_PI`? I had to manually change it to `Double.pi`.

**Comment by jesster2k10** [comment]
@adrianodiasx93 Any update on this?
