### ISSUE TITLE
Build errors in Swift file

### ISSUE THREAD

**Issue by Humanplus91** [entotsu/TKSubmitTransition#41]
When building it's giving the following error, 

Installed through CocoaPods link v2.0, Xcode 9 - Swift 3 - iOS11

"TransitionSubmitButton.Swift"
Property cannot be marked @IBInspectable because its type cannot be represented in Objective-C

Any idea's?

**Comment by colealanroberts** [comment]
Seeing the same issue.

**Comment by colealanroberts** [comment]
Referencing this commit: https://github.com/entotsu/TKSubmitTransition/commit/1230515641cded28e9af3768ab75fc064998e62f

and specifically

```
-    @IBInspectable open var normalCornerRadius:CGFloat? = 0.0{
 +    @IBInspectable open var normalCornerRadius:CGFloat = 0.0 {
          didSet {
 -            self.layer.cornerRadius = normalCornerRadius!
 +            self.layer.cornerRadius = normalCornerRadius
          }
      }
```

Fixed the build issue for me!

**Comment by RishabhTayal** [comment]
Is this still an issue? I don't see any compile error in swift 3.

**Comment by RishabhTayal** [comment]
@Humanplus91 You can use the swift4 branch like this:

```
  pod 'TKSubmitTransition', :git => 'https://github.com/entotsu/TKSubmitTransition.git', :branch => 'swift4'
```
Closing this now.
