### ISSUE TITLE
Sample code is not compiling in Swift 4

### ISSUE THREAD

**Issue by haroldogtf** [entotsu/TKSubmitTransition#45]
Sample code is not compiling in Swift 4.

**Comment by RishabhTayal** [comment]
@haroldogtf Which branch are you using?

**Comment by haroldogtf** [comment]
I just downloaded the .zip option. Probably is master.




probably
--

**Comment by RishabhTayal** [comment]
`master` is not swift 4 yet. Use the `swift4` branch. Closing it for now.
