### ISSUE TITLE
Missing argument for parameter #2 in call

### ISSUE THREAD

**Issue by TimaShams** [entotsu/TKSubmitTransition#48]
![screen shot 1439-06-17 at 12 54 21 pm](https://user-images.githubusercontent.com/12412039/36968709-6a6c4754-2074-11e8-973e-5d23441f4be7.png)

How to fix this?

**Comment by RishabhTayal** [comment]
@TimaShams Which version of swift are you using? Which version of the pod are you using? Are you pointing to a specific branch?

**Comment by Halcao** [comment]
@RishabhTayal I got the same error and I am using the package download from master branch. The error is in ViewController.swift, line 28. 
And the prototype of the function is `open func animate(_ duration: TimeInterval,_ animation: CAMediaTimingFunction, completion:(()->())?)`

**Comment by RishabhTayal** [comment]
Are you using swift 3 or swift 4 version?

Regards,
Rishabh Tayal
rtayal11@gmail.com

**Comment by Halcao** [comment]
Yes, I am using Swift 3.2
Rishabh Tayal <notifications@github.com>于2018年3月9日 周五上午4:18写道：

> Are you using swift 3 or swift 4 version?
>
> Regards,
> Rishabh Tayal
> rtayal11@gmail.com
>
>

**Comment by Halcao** [comment]
@RishabhTayal I am not using Pod. I just downloaded the source code from the master branch.

**Comment by RishabhTayal** [comment]
If you are not using cocoapod, check out the specific branch or tag depending on your swift version.

https://github.com/entotsu/TKSubmitTransition/blob/master/README.md#installation

**Comment by sasquatchgit** [comment]
I am using Swift 4 and getting this error

**Comment by sasquatchgit** [comment]
@TimaShams For now, you can solve this by providing an argument. A default `CAMediaTimingFunction` will do.

```
button.animate(1, CAMediaTimingFunction(name: kCAMediaTimingFunctionDefault) ){
                        //your completion
                    }
```
