### ISSUE TITLE
TKFadeInAnimator / UITransitionContextViewKey.from nil on iOS13

### ISSUE THREAD

**Issue by psuarezglb** [entotsu/TKSubmitTransition#61]
on the TKFadeInAnimator
func animateTransition
line 30
let fromView = transitionContext.view(forKey: UITransitionContextViewKey.from)!

I'm getting a nil on the UITransitionContextViewKey.from 

running on Xcode 11 / iOS 13

**Comment by JirkaKrivanek** [comment]
This is my case too... Any chance to fix it or shall we get rid of this dependency?

**Comment by sandeepbol** [comment]
Please allow a few days' time. will try to get to it, this weekend. Thanks.

**Comment by TheM4hd1** [comment]
set `modalPresentationStyle` to `.custom` and it fixes.
```swift
let vc = YourVC()
vc.modalPresentationStyle = .custom
```

**Comment by sandeepbol** [comment]
Please use

`pod 'TKSubmitTransition', :git => 'https://github.com/entotsu/TKSubmitTransition.git'`

for xCode11 and iOS 13 with standard steps. It will working fine. 

I am closing this.

**Comment by v-ken** [comment]
This worked for me:
```
let vc = YourVC()
vc.modalPresentationStyle = .fullScreen
```

**Comment by sandeepbol** [comment]
Thanks @v-ken. Going to post a generic solution that works for all modalPresentationStyle later tonight.
