### ISSUE TITLE
Stop Animation on returnToOriginalState()

### ISSUE THREAD

**Issue by jtezanos** [entotsu/TKSubmitTransition#7]
I just made a quick change to returnToOriginalState() in TKSubmitButton.swift by adding self.spiner.stopAnimation() to the function. Is that how you intended to cancel the spinner?

**Comment by wwdc14** [comment]
Here https://github.com/wwdc14/HySubmitTransitionObjective-C

**Comment by MartinQue** [comment]
greate but how do you get that in swift? ...
